/*
 * OiOi content management API
 * OiOi content management API spec
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fi.metatavu.oioi.cm.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
