/**
 * OiOi content management API
 * OiOi content management API spec
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ErrorResponse { 
    /**
     * The error message
     */
    readonly message?: string;
}
export interface ErrorResponseOpt { 
    /**
     * The error message
     */
    readonly message?: string;
}
