/*
 * OiOi content management API
 * OiOi content management API spec
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fi.metatavu.oioi.cm.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.metatavu.oioi.cm.client.model.MediaType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;

/**
 * ApplicationStructureItem
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-30T18:12:54.816416+03:00[Europe/Helsinki]")public class ApplicationStructureItem {

  @JsonProperty("path")

  private String path = null;

  @JsonProperty("allowedTypes")

  private List<MediaType> allowedTypes = new ArrayList<>();
  public ApplicationStructureItem path(String path) {
    this.path = path;
    return this;
  }

  

  /**
  * Get path
  * @return path
  **/
  @Schema(required = true, description = "")
  public String getPath() {
    return path;
  }
  public void setPath(String path) {
    this.path = path;
  }
  public ApplicationStructureItem allowedTypes(List<MediaType> allowedTypes) {
    this.allowedTypes = allowedTypes;
    return this;
  }

  public ApplicationStructureItem addAllowedTypesItem(MediaType allowedTypesItem) {
    this.allowedTypes.add(allowedTypesItem);
    return this;
  }

  /**
  * Get allowedTypes
  * @return allowedTypes
  **/
  @Schema(required = true, description = "")
  public List<MediaType> getAllowedTypes() {
    return allowedTypes;
  }
  public void setAllowedTypes(List<MediaType> allowedTypes) {
    this.allowedTypes = allowedTypes;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplicationStructureItem applicationStructureItem = (ApplicationStructureItem) o;
    return Objects.equals(this.path, applicationStructureItem.path) &&
        Objects.equals(this.allowedTypes, applicationStructureItem.allowedTypes);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(path, allowedTypes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplicationStructureItem {\n");
    
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    allowedTypes: ").append(toIndentedString(allowedTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
