/*
 * OiOi content management API
 * OiOi content management API spec
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fi.metatavu.oioi.cm.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * DeviceApplication
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-30T18:12:54.816416+03:00[Europe/Helsinki]")public class DeviceApplication {

  @JsonProperty("id")

  private UUID id = null;

  @JsonProperty("deviceId")

  private UUID deviceId = null;

  @JsonProperty("applicationId")

  private UUID applicationId = null;

  @JsonProperty("createdAt")

  private OffsetDateTime createdAt = null;

  @JsonProperty("modifiedAt")

  private OffsetDateTime modifiedAt = null;
  /**
  * Device application id.
  * @return id
  **/
  @Schema(description = "Device application id.")
  public UUID getId() {
    return id;
  }
  public DeviceApplication deviceId(UUID deviceId) {
    this.deviceId = deviceId;
    return this;
  }

  

  /**
  * Device id.
  * @return deviceId
  **/
  @Schema(required = true, description = "Device id.")
  public UUID getDeviceId() {
    return deviceId;
  }
  public void setDeviceId(UUID deviceId) {
    this.deviceId = deviceId;
  }
  public DeviceApplication applicationId(UUID applicationId) {
    this.applicationId = applicationId;
    return this;
  }

  

  /**
  * Application id.
  * @return applicationId
  **/
  @Schema(required = true, description = "Application id.")
  public UUID getApplicationId() {
    return applicationId;
  }
  public void setApplicationId(UUID applicationId) {
    this.applicationId = applicationId;
  }
  /**
  * Creation time
  * @return createdAt
  **/
  @Schema(description = "Creation time")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }
  /**
  * Last modification time
  * @return modifiedAt
  **/
  @Schema(description = "Last modification time")
  public OffsetDateTime getModifiedAt() {
    return modifiedAt;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceApplication deviceApplication = (DeviceApplication) o;
    return Objects.equals(this.id, deviceApplication.id) &&
        Objects.equals(this.deviceId, deviceApplication.deviceId) &&
        Objects.equals(this.applicationId, deviceApplication.applicationId) &&
        Objects.equals(this.createdAt, deviceApplication.createdAt) &&
        Objects.equals(this.modifiedAt, deviceApplication.modifiedAt);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, deviceId, applicationId, createdAt, modifiedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceApplication {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
