/*
 * OiOi content management API
 * OiOi content management API spec
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fi.metatavu.oioi.cm.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.metatavu.oioi.cm.client.model.MediaType;
import fi.metatavu.oioi.cm.client.model.ResourceStyle;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Resource
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-30T18:12:54.816416+03:00[Europe/Helsinki]")public class Resource {

  @JsonProperty("id")

  private UUID id = null;

  @JsonProperty("parentId")

  private UUID parentId = null;

  @JsonProperty("deviceApplicationId")

  private UUID deviceApplicationId = null;

  @JsonProperty("type")

  private MediaType type = null;

  @JsonProperty("data")

  private String data = null;

  @JsonProperty("styles")

  private ResourceStyle styles = null;

  @JsonProperty("createdAt")

  private OffsetDateTime createdAt = null;

  @JsonProperty("modifiedAt")

  private OffsetDateTime modifiedAt = null;
  /**
  * Device application id.
  * @return id
  **/
  @Schema(description = "Device application id.")
  public UUID getId() {
    return id;
  }
  public Resource parentId(UUID parentId) {
    this.parentId = parentId;
    return this;
  }

  

  /**
  * Parent resource id
  * @return parentId
  **/
  @Schema(description = "Parent resource id")
  public UUID getParentId() {
    return parentId;
  }
  public void setParentId(UUID parentId) {
    this.parentId = parentId;
  }
  public Resource deviceApplicationId(UUID deviceApplicationId) {
    this.deviceApplicationId = deviceApplicationId;
    return this;
  }

  

  /**
  * Device application id.
  * @return deviceApplicationId
  **/
  @Schema(description = "Device application id.")
  public UUID getDeviceApplicationId() {
    return deviceApplicationId;
  }
  public void setDeviceApplicationId(UUID deviceApplicationId) {
    this.deviceApplicationId = deviceApplicationId;
  }
  public Resource type(MediaType type) {
    this.type = type;
    return this;
  }

  

  /**
  * Get type
  * @return type
  **/
  @Schema(description = "")
  public MediaType getType() {
    return type;
  }
  public void setType(MediaType type) {
    this.type = type;
  }
  public Resource data(String data) {
    this.data = data;
    return this;
  }

  

  /**
  * Resource data, either URL on images, videos, etc and text data on text resources
  * @return data
  **/
  @Schema(description = "Resource data, either URL on images, videos, etc and text data on text resources")
  public String getData() {
    return data;
  }
  public void setData(String data) {
    this.data = data;
  }
  public Resource styles(ResourceStyle styles) {
    this.styles = styles;
    return this;
  }

  

  /**
  * Get styles
  * @return styles
  **/
  @Schema(description = "")
  public ResourceStyle getStyles() {
    return styles;
  }
  public void setStyles(ResourceStyle styles) {
    this.styles = styles;
  }
  /**
  * Creation time
  * @return createdAt
  **/
  @Schema(description = "Creation time")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }
  /**
  * Last modification time
  * @return modifiedAt
  **/
  @Schema(description = "Last modification time")
  public OffsetDateTime getModifiedAt() {
    return modifiedAt;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Resource resource = (Resource) o;
    return Objects.equals(this.id, resource.id) &&
        Objects.equals(this.parentId, resource.parentId) &&
        Objects.equals(this.deviceApplicationId, resource.deviceApplicationId) &&
        Objects.equals(this.type, resource.type) &&
        Objects.equals(this.data, resource.data) &&
        Objects.equals(this.styles, resource.styles) &&
        Objects.equals(this.createdAt, resource.createdAt) &&
        Objects.equals(this.modifiedAt, resource.modifiedAt);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, parentId, deviceApplicationId, type, data, styles, createdAt, modifiedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Resource {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    deviceApplicationId: ").append(toIndentedString(deviceApplicationId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    styles: ").append(toIndentedString(styles)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
