/*
 * OiOi content management API
 * OiOi content management API spec
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fi.metatavu.oioi.cm.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ResourceStyle
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-30T18:12:54.816416+03:00[Europe/Helsinki]")public class ResourceStyle {

  @JsonProperty("backgroundColor")

  private String backgroundColor = null;

  @JsonProperty("foregroundColor")

  private String foregroundColor = null;
  public ResourceStyle backgroundColor(String backgroundColor) {
    this.backgroundColor = backgroundColor;
    return this;
  }

  

  /**
  * Get backgroundColor
  * @return backgroundColor
  **/
  @Schema(description = "")
  public String getBackgroundColor() {
    return backgroundColor;
  }
  public void setBackgroundColor(String backgroundColor) {
    this.backgroundColor = backgroundColor;
  }
  public ResourceStyle foregroundColor(String foregroundColor) {
    this.foregroundColor = foregroundColor;
    return this;
  }

  

  /**
  * Get foregroundColor
  * @return foregroundColor
  **/
  @Schema(description = "")
  public String getForegroundColor() {
    return foregroundColor;
  }
  public void setForegroundColor(String foregroundColor) {
    this.foregroundColor = foregroundColor;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceStyle resourceStyle = (ResourceStyle) o;
    return Objects.equals(this.backgroundColor, resourceStyle.backgroundColor) &&
        Objects.equals(this.foregroundColor, resourceStyle.foregroundColor);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(backgroundColor, foregroundColor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceStyle {\n");
    
    sb.append("    backgroundColor: ").append(toIndentedString(backgroundColor)).append("\n");
    sb.append("    foregroundColor: ").append(toIndentedString(foregroundColor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
